### ISSUE TITLE
formalize response

### ISSUE THREAD

**Issue by chazkiker2** [Light-Labs/ryder-client#12]
we should formalize a response struct of some sort that all "communication" methods can respond with.

I hate that `ryder_serial.send(SOME_COMMAND)` can respond with a number (to signify status) or a string (to hold data). 

it leads to client code that looks like this: 

```typescript
const res = await ryder_serial.send(SOME_COMMAND);

if (typeof res == "number") {
    // do something with number 
    // such as compare to RyderSerial.RESPONSE_OK
}
else {
    // try to parse number? 
    // throw error? 
}
```

We should have an un-ambiguous response type with clear definition for response_status, data, etc.

super open to suggestions/ideas for properties on this response, but it would be nice to not have to check response with `typeof` statements on client end

**Comment by friedger** [comment]
Should we use clarity response type? Is that too inefficient?

Example responses:

error code uint 301 `(err u301)`:
0x08010000000000000000000000000000012d

ok with data `(ok (tuple (dx u65461361134) (dy u75021172153)))`:
0x070c000000020264780100000000000000000000000f3dcd19ee02647901000000000000000000000011779c3db9

**Comment by MarvinJanssen** [comment]
Closed for inactivity.
